### ISSUE TITLE
git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaSoftware/abf-console-client#27]
nikolanp@rosa2021 ~> abf get blacksaber/Serviio -b master
Схема файла конфигурации была изменена либо файл поврежден, перезапускаем настройку конфигурации
ABF URL [https://abf.rosalinux.ru]: 
User [nikolanp]: blacksaber           
Password: 
Default project branch [master]: 
Default project owner [blacksaber]: 
Default platform [rosa2021.1]: 
File-store URL [https://file-store.rosalinux.ru]: 
Default publishing status for new builds [default]: 
Конфигурация успешно завершена
Теперь вы можете запустить "abf locate update-recursive -d PATH", где PATH - это ваша директория с клонированными проектами ABF. Это позволит вам использовать команду "abfcd <project>" для перехода в директорию проекта.

Клонирование в «Serviio»…
git@github.com: Permission denied (publickey).
fatal: Не удалось прочитать из внешнего репозитория.

Удостоверьтесь, что у вас есть необходимые права доступа
и репозиторий существует.
nikolanp@rosa2021 ~ [1]>

**Comment by fedya** [comment]
>git@github.com: Permission denied (publickey).
Ну оно идет на гитхаб а не на abf.io
Рекомендую обратить внимание на содержимое ~/.abfcfg

**Comment by saber716rus** [comment]
[abfcfg.zip](https://github.com/OpenMandrivaSoftware/abf-console-client/files/7576142/abfcfg.zip)
да уже по всякому редактировал, но одно и тоже.

**Comment by fedya** [comment]
1.Очень не советую публиковать конфиги с паролями.
2. git_uri указывает не туда

**Comment by saber716rus** [comment]
> 1.Очень не советую публиковать конфиги с паролями.
> 2. git_uri указывает не туда

Я уже пробовал и abf.io, одна и тажа ошибка.

**Comment by fedya** [comment]
git_uri = ssh://git@abf.rosalinux.ru
так должно быть

**Comment by saber716rus** [comment]
Спасибо.
