### ISSUE TITLE
[FR] add rpmbuild -p

### ISSUE THREAD

**Issue by mikhailnov** [OpenMandrivaSoftware/abf-console-client#30]
Currently `abf rpmbuild` can run `rpmbuild -bb` and `rpmbuild -bs`, please add running `rpmbuild -bp` as `abf rpmbuild -b p` to quickly check appliability of patches.

**Comment by fedya** [comment]
https://github.com/OpenMandrivaSoftware/abf-console-client/commit/3e3c28d862a084b66ec7f92f62dc1f7560913f86

**Comment by mikhailnov** [comment]
Thanks!
