### ISSUE TITLE
[Bug]: не исполняется команда --auto-create-container

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaSoftware/abf-console-client#40]
Здравствуйте. Обнаружил, что команда не работает и это уже не первый раз
 ![Screenshot_2022-11-21-13-40-45-274_ru.yandex.searchplugin.jpg](https://user-images.githubusercontent.com/22714555/203030590-1075a9a3-2ce7-4f3d-a8d2-30b1a20276a8.jpg)

**Comment by fedya** [comment]
А какая команда не рабоатет не понятно

**Comment by saber716rus** [comment]
Я же написал, что команда для создания контейнераВот это команда, она в названии баги --auto-create-container19:24, 21 ноября 2022 г., Alexander Stefanov ***@***.***>:
А какая команда не рабоатет не понятно

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
С Уважением, Николай.Специалист IT-систем.+79625490833 (whatsapp)telegram: https://t.me/Saber716RUSinstagram: @saber716russkype: nicksab1491

**Comment by fedya** [comment]
Она совершенно точно работает, потому что таким образом каждый день создаются десятки автоматических апдейтом для пакетов.

**Comment by saber716rus** [comment]
> Она совершенно точно работает, потому что таким образом каждый день создаются десятки автоматических апдейтов для пакетов.
> Рекомендую описать **подробнее** с выводом консоли 

saber716rus@localhost ~/exa (rosa2021.1)> abf build -b rosa2021.1 --skip-personal -r rosa2021.1/main -s saber716rus_personal/main --auto-create-container --update-type newpackage --auto-publish                 Could not resolve a platform to save to from the branch name "rosa2021.1".                                                                  Arches are assumed to be [i686, x86_64, aarch64, riscv64, e2kv4]      Task saber716rus/exa|rosa2021.1|saber716rus_personal/main|i686 has been sent. Build task id is 4177441                                      Task saber716rus/exa|rosa2021.1|saber716rus_personal/main|x86_64 has been sent. Build task id is 4177442                                    Task saber716rus/exa|rosa2021.1|saber716rus_personal/main|aarch64 has been sent. Build task id is 4177443                                   Task saber716rus/exa|rosa2021.1|saber716rus_personal/main|riscv64 has been sent. Build task id is 4177444                                   Task saber716rus/exa|rosa2021.1|saber716rus_personal/main|e2kv4 has been sent. Build task id is 4177445                                     saber716rus@localhost ~/exa (rosa2021.1)>

**Comment by saber716rus** [comment]
Контейнер не создан.
![Screenshot_2022-11-22-03-30-42-044_ru.yandex.searchplugin.jpg](https://user-images.githubusercontent.com/22714555/203185503-7e52d599-bd4f-4e05-a3cb-98ac132fd973.jpg)

**Comment by fedya** [comment]
Could not resolve a platform to save to from the branch name
 уберите эту опцию

**Comment by saber716rus** [comment]
Убираю, то ошибка выходит, так как не указана платформа.

**Comment by ilfat12** [comment]
У себя на персональной репе проверил - подтверждаю, контейнер не создается. Может есть ограничение для создания контейнеров при сборке из персонального репозитория?
А ругань, что не может определить платформу при сборке из персоналки, всегда была.

Я еще заметил, что алиасы не работают...

**Comment by mikhailnov** [comment]
В абф-клиента `--auto-create-container` работает, это вопрос к движку абф. Попробуйте добавить `--auto-publish-status none`, по-моему, тогда создастся в описанной ситуации контейнер.

**Comment by saber716rus** [comment]
Ввел команду
abf build -b rosa2021.1 -s saber716rus_personal/main -r rosa2021.1/main --skip-personal --update-type newpackage --auto-create-container --auto-publish-status none

**Comment by saber716rus** [comment]
Сейчас создало. Чего и требовалось от команды. Видимо Миша был прав. Видимо надо баг на rosa abf поднимать.
