### ISSUE TITLE
abf does not recognize sources from .abf.yml

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/abf-console-client#8]
abf does not recognize sources from .abf.yml

```

[tpg@tpg-80xl kernel-release-clang]$ abf put -m "new version 5.3.11"
Traceback (most recent call last):
  File "/usr/bin/abf", line 1769, in <module>
    command_line.func()
  File "/usr/bin/abf", line 817, in put
    error_count = upload_files(models, min_size, remove_files=not command_line.do_not_remove_files, path=path, upload_all=command_line.upload_all)
  File "/usr/lib/python3.7/site-packages/abf/console/misc.py", line 546, in upload_files
    filesize = os.stat(source).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'patch-5.3.11.xz'
```

**Comment by fedya** [comment]
abf put is uploading file first
in your case no such file to upload and you got an error.
Solution: download file first

**Comment by tpgxyz** [comment]
@fedya why i should download source if i'm just doing operations on .spec file ?
I was always able to "abf put" even if .abf.yml have right source.
What about RPMS that does not provide any source ? abf put will not work there.
 
```
[tpg@tpg-80xl microdnf]$ abf put -m "bump version on buildrequires"
Traceback (most recent call last):
  File "/usr/bin/abf", line 1769, in <module>
    command_line.func()
  File "/usr/bin/abf", line 817, in put
    error_count = upload_files(models, min_size, remove_files=not command_line.do_not_remove_files, path=path, upload_all=command_line.upload_all)
  File "/usr/lib/python3.7/site-packages/abf/console/misc.py", line 546, in upload_files
    filesize = os.stat(source).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'microdnf-3.0.2.tar.gz'

[tpg@tpg-80xl microdnf]$ ls -a
.  ..  .abf.yml  .git  microdnf.spec

```

**Comment by fedya** [comment]
abf put it's about **uploading** sources to fstore with commit message, if you want to just bump release use git commit

**Comment by tpgxyz** [comment]
@fedya Previously i've been using:
abf store foo.tar.xz
abf put -m "new version"

Now i need to use different commands :(

Can you please fix it ? i.e. if source from spec exist in .abf.yml and sha1 is on fstore then do nothing :)

**Comment by fedya** [comment]
> abf store foo.tar.xz
This command does not remove tar file when you run it
it's mean that **abf put** does not show error about 'source not found' because it exist in current dir.

I never changed this part of code in abf-c-c and it works like it was 1+ years ago.

You expect same behaviour as it is with git commit -m 'message' ?

**Comment by tpgxyz** [comment]
@fedya After last updates things got broken.
abf put -m "bla bla bla" always needs to have downloades sources.
I'd expect that `abf put` first check if source is inside .abf.yml already and was pushed in previous commits.

**Comment by fedya** [comment]
@tpgxyz 
but i never changed this part of code :)
